import localFont from 'next/font/local'
import '../globals.css'

import Navbar from '../../components/shared/Navbar'
import Footer from '../../components/shared/Footer'
import { ShopContextProvider } from '../../context/ShopContext'
import SearchBar from '../../components/UI/SearchBar'

const myFont = localFont({
  src: '../../public/font/Tanha.ttf',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html dir='rtl' lang='fa'>
      <body className={myFont.className}>
        <ShopContextProvider>
          <Navbar />
          <SearchBar />
          <main className=''>{children}</main>
          <Footer />
        </ShopContextProvider>
      </body>
    </html>
  )
}
