import {Poppins } from "next/font/google";
import "../globals.css";

const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={poppins.variable}
    >
      <body className="min-h-full flex flex-col">
        <main>
        {children}
        </main>
        </body>
    </html>
  );
}
