import localFont from 'next/font/local'
import '../globals.css'

import Navbar from '../../components/shared/Navbar'
import Footer from '../../components/shared/Footer'

const myFont = localFont({
  src: '../../public/font/irsansb.ttf',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html dir='rtl' lang='fa' >
      <body className={myFont.className} >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
